"""Action handlers that wrap dapr-swe agent runners for workflow-builder orchestration.

Each handler takes (input_data, node_outputs) and returns
{"success": bool, "data": dict, "error": str | None}.
"""

from __future__ import annotations

import asyncio
import logging
from typing import Any

import httpx

from src.integrations.github_app import get_github_app_installation_token
from src.sandbox.openshell import OpenShellBackend, create_openshell_sandbox

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _resolve(input_data: dict, node_outputs: dict, key: str, node_label: str = "") -> Any:
    """Resolve a value from input_data or a previous node's output.

    Searches: input_data → node_outputs[*].data → node_outputs[*].data.data (nested).
    The orchestrator stores node results as: {data: {success, data: {actual_fields}}}.
    """
    if key in input_data:
        return input_data[key]
    # Search all previous node outputs
    for nid, out in node_outputs.items():
        if not isinstance(out, dict):
            continue
        # Direct in output
        if key in out:
            return out[key]
        # In output.data
        data = out.get("data", {})
        if isinstance(data, dict):
            if key in data:
                return data[key]
            # In output.data.data (nested function-router response)
            inner = data.get("data", {})
            if isinstance(inner, dict) and key in inner:
                return inner[key]
    return None


def _reconnect_sandbox(sandbox_id: str) -> OpenShellBackend:
    """Reconnect to an existing sandbox by its ID."""
    return create_openshell_sandbox(sandbox_id=sandbox_id)


def _build_pr_body(plan: dict, issue_number: int) -> str:
    """Build a PR description from the plan."""
    summary = plan.get("summary", "Automated implementation")
    steps = plan.get("steps", [])

    parts = [
        "## Summary",
        "",
        summary,
        "",
        f"Closes #{issue_number}",
        "",
    ]

    if steps:
        parts.append("## Changes")
        parts.append("")
        for step in steps:
            parts.append(f"- **{step.get('title', '')}**: {step.get('description', '')}")
        parts.append("")

    parts.append("---")
    parts.append("*Generated by dapr-swe*")

    return "\n".join(parts)


# ---------------------------------------------------------------------------
# 1. Initialize -- create sandbox, clone repo, read AGENTS.md
# ---------------------------------------------------------------------------


def handle_initialize(input_data: dict, node_outputs: dict) -> dict:
    """Create sandbox, clone the repo, and read AGENTS.md.

    Expects owner and repo in input_data (or from a trigger node output).
    Returns sandbox_id, working_dir, agents_md, github_token.
    """
    owner = _resolve(input_data, node_outputs, "owner")
    repo = _resolve(input_data, node_outputs, "repo")

    if not owner or not repo:
        return {"success": False, "data": {}, "error": "Missing required fields: owner, repo"}

    # Get GitHub App installation token
    # Use thread executor to avoid event loop conflicts with uvicorn
    import concurrent.futures

    with concurrent.futures.ThreadPoolExecutor() as pool:
        token = pool.submit(
            lambda: asyncio.run(get_github_app_installation_token())
        ).result(timeout=30)

    if not token:
        return {"success": False, "data": {}, "error": "Failed to obtain GitHub App installation token"}

    # Create sandbox
    try:
        sandbox = create_openshell_sandbox()
    except Exception as exc:
        return {"success": False, "data": {}, "error": f"Failed to create sandbox: {exc}"}

    sandbox_id = sandbox.id
    working_dir = f"/sandbox/{repo}"

    # Clone repository
    clone_url = f"https://x-access-token:{token}@github.com/{owner}/{repo}.git"
    result = sandbox.execute(
        f"git clone --depth=50 {clone_url} {working_dir}",
        timeout=120,
    )
    if result.exit_code != 0:
        return {
            "success": False,
            "data": {"sandbox_id": sandbox_id},
            "error": f"Failed to clone repository: {result.output}",
        }

    # Store credentials for later push
    sandbox.execute(
        f"echo 'https://x-access-token:{token}@github.com' > /tmp/.git-credentials",
        timeout=10,
    )

    # Configure git identity
    sandbox.execute(
        f"cd {working_dir} && "
        "git config user.email 'dapr-swe[bot]@users.noreply.github.com' && "
        "git config user.name 'dapr-swe[bot]'",
        timeout=10,
    )

    # Read AGENTS.md if present
    agents_md = ""
    agents_result = sandbox.execute(f"cat {working_dir}/AGENTS.md 2>/dev/null", timeout=10)
    if agents_result.exit_code == 0 and agents_result.output.strip():
        agents_md = agents_result.output.strip()

    return {
        "success": True,
        "data": {
            "sandbox_id": sandbox_id,
            "working_dir": working_dir,
            "agents_md": agents_md,
            "github_token": token,
        },
        "error": None,
    }


# ---------------------------------------------------------------------------
# 2. Plan -- run PlannerAgent
# ---------------------------------------------------------------------------


def handle_plan(input_data: dict, node_outputs: dict) -> dict:
    """Run the PlannerAgent to produce an implementation plan.

    Expects sandbox_id and issue context (issue_number, title, body, etc.).
    """
    from src.agents.planner import run_planner

    sandbox_id = _resolve(input_data, node_outputs, "sandbox_id")
    if not sandbox_id:
        return {"success": False, "data": {}, "error": "Missing required field: sandbox_id"}

    sandbox = _reconnect_sandbox(sandbox_id)

    # Build issue context from all available fields
    issue_context = {}
    for key in ("owner", "repo", "issue_number", "title", "body", "comments",
                "sender", "working_dir", "agents_md", "github_token"):
        val = _resolve(input_data, node_outputs, key)
        if val is not None:
            issue_context[key] = val

    try:
        plan = run_planner(sandbox, issue_context)
    except Exception as exc:
        logger.exception("PlannerAgent failed")
        return {"success": False, "data": {}, "error": f"PlannerAgent failed: {exc}"}

    return {
        "success": True,
        "data": {
            "plan": plan,
            "summary": plan.get("summary", ""),
            "step_count": len(plan.get("steps", [])),
        },
        "error": None,
    }


# ---------------------------------------------------------------------------
# 3. Develop -- run DeveloperAgent for a single step
# ---------------------------------------------------------------------------


def handle_develop(input_data: dict, node_outputs: dict) -> dict:
    """Run the DeveloperAgent for a single plan step.

    Expects sandbox_id, step (dict), and issue/plan context.
    """
    from src.agents.developer import run_developer

    sandbox_id = _resolve(input_data, node_outputs, "sandbox_id")
    if not sandbox_id:
        return {"success": False, "data": {}, "error": "Missing required field: sandbox_id"}

    sandbox = _reconnect_sandbox(sandbox_id)

    # Build issue context from all available sources
    issue_context = {}
    for key in ("owner", "repo", "issue_number", "title", "body", "comments",
                "sender", "working_dir", "agents_md", "github_token"):
        val = _resolve(input_data, node_outputs, key)
        if val is not None:
            issue_context[key] = val

    plan = _resolve(input_data, node_outputs, "plan") or {}

    # Get step(s) to implement
    step = _resolve(input_data, node_outputs, "step")
    steps = plan.get("steps", [])

    # If no specific step, implement all steps from the plan
    if not step and steps:
        results = []
        for i, s in enumerate(steps):
            logger.info("Implementing step %d/%d: %s", i + 1, len(steps), s.get("title", ""))
            try:
                r = run_developer(sandbox=sandbox, step=s, issue_context=issue_context, plan=plan)
                results.append(r)
            except Exception as exc:
                logger.warning("Step %d failed: %s", i + 1, exc)
                results.append({"status": "error", "error": str(exc)})
        return {
            "success": True,
            "data": {"status": "completed", "steps_completed": len(results), "results": results},
        }

    if not step:
        # No step and no plan steps — implement based on issue description
        step = {
            "title": "Implement changes",
            "description": issue_context.get("body", issue_context.get("title", "")),
            "files": [],
        }

    try:
        result = run_developer(
            sandbox=sandbox,
            step=step,
            issue_context=issue_context,
            plan=plan,
        )
    except Exception as exc:
        logger.exception("DeveloperAgent failed")
        return {"success": False, "data": {}, "error": f"DeveloperAgent failed: {exc}"}

    return {
        "success": True,
        "data": {
            "status": result.get("status", "unknown"),
            "files_changed": result.get("files_changed", []),
        },
        "error": None,
    }


# ---------------------------------------------------------------------------
# 4. Review -- run ReviewerAgent on the full diff
# ---------------------------------------------------------------------------


def handle_review(input_data: dict, node_outputs: dict) -> dict:
    """Run the ReviewerAgent on the current diff.

    Expects sandbox_id, working_dir, and issue/plan context.
    """
    from src.agents.reviewer import run_reviewer

    sandbox_id = _resolve(input_data, node_outputs, "sandbox_id")
    working_dir = _resolve(input_data, node_outputs, "working_dir")

    if not sandbox_id:
        return {"success": False, "data": {}, "error": "Missing required field: sandbox_id"}
    if not working_dir:
        return {"success": False, "data": {}, "error": "Missing required field: working_dir"}

    sandbox = _reconnect_sandbox(sandbox_id)

    # Get the full diff
    diff_result = sandbox.execute(f"cd {working_dir} && git diff HEAD", timeout=60)
    diff = diff_result.output or ""

    # If no unstaged changes, check for staged changes or commits ahead of origin
    if not diff.strip():
        diff_result = sandbox.execute(
            f"cd {working_dir} && git diff origin/main...HEAD",
            timeout=60,
        )
        diff = diff_result.output or ""

    if not diff.strip():
        return {
            "success": True,
            "data": {"approved": True, "feedback": "No changes to review", "suggestions": []},
            "error": None,
        }

    # Build issue context and plan
    issue_context = {}
    for key in ("owner", "repo", "issue_number", "title", "body"):
        val = _resolve(input_data, node_outputs, key)
        if val is not None:
            issue_context[key] = val

    plan = _resolve(input_data, node_outputs, "plan") or {}

    try:
        review = run_reviewer(diff=diff, issue_context=issue_context, plan=plan)
    except Exception as exc:
        logger.exception("ReviewerAgent failed")
        return {"success": False, "data": {}, "error": f"ReviewerAgent failed: {exc}"}

    return {
        "success": True,
        "data": {
            "approved": review.get("approved", False),
            "feedback": review.get("feedback", ""),
            "suggestions": review.get("suggestions", []),
        },
        "error": None,
    }


# ---------------------------------------------------------------------------
# 5. Commit & PR -- stage, commit, push, and open a GitHub PR
# ---------------------------------------------------------------------------


def handle_commit_pr(input_data: dict, node_outputs: dict) -> dict:
    """Stage changes, create branch, commit, push, and open a GitHub PR.

    Expects sandbox_id, working_dir, owner, repo, issue_number, github_token.
    """
    sandbox_id = _resolve(input_data, node_outputs, "sandbox_id")
    working_dir = _resolve(input_data, node_outputs, "working_dir")
    owner = _resolve(input_data, node_outputs, "owner")
    repo = _resolve(input_data, node_outputs, "repo")
    issue_number = _resolve(input_data, node_outputs, "issue_number")
    token = _resolve(input_data, node_outputs, "github_token")
    title = _resolve(input_data, node_outputs, "title") or "Untitled issue"
    plan = _resolve(input_data, node_outputs, "plan") or {}

    for field, val in [("sandbox_id", sandbox_id), ("working_dir", working_dir),
                       ("owner", owner), ("repo", repo),
                       ("issue_number", issue_number), ("github_token", token)]:
        if not val:
            return {"success": False, "data": {}, "error": f"Missing required field: {field}"}

    sandbox = _reconnect_sandbox(sandbox_id)
    branch_name = f"dapr-swe/issue-{issue_number}"

    # Check for actual changes
    status_result = sandbox.execute(f"cd {working_dir} && git status --porcelain", timeout=10)
    if not status_result.output.strip():
        return {
            "success": True,
            "data": {"pr_url": "", "branch": branch_name, "status": "no_changes"},
            "error": None,
        }

    # Configure git user, create branch, stage, commit
    commit_result = sandbox.execute(
        f"cd {working_dir} && "
        "git config user.email 'dapr-swe[bot]@users.noreply.github.com' && "
        "git config user.name 'dapr-swe[bot]' && "
        f"git checkout -b {branch_name} && "
        "git add -A && "
        f'git commit -m "fix: {title} [closes #{issue_number}]"',
        timeout=60,
    )
    if commit_result.exit_code != 0:
        return {
            "success": False,
            "data": {"branch": branch_name},
            "error": f"Failed to commit: {commit_result.output}",
        }

    # Push
    push_result = sandbox.execute(
        f"cd {working_dir} && git push -u origin {branch_name}",
        timeout=120,
    )
    if push_result.exit_code != 0:
        return {
            "success": False,
            "data": {"branch": branch_name},
            "error": f"Push failed: {push_result.output}",
        }

    # Open PR via GitHub API
    pr_body = _build_pr_body(plan, int(issue_number))
    pr_data = {
        "title": f"fix: {title} [closes #{issue_number}]",
        "head": branch_name,
        "base": "main",
        "body": pr_body,
        "draft": True,
    }

    try:
        with httpx.Client(timeout=30) as client:
            resp = client.post(
                f"https://api.github.com/repos/{owner}/{repo}/pulls",
                headers={
                    "Authorization": f"Bearer {token}",
                    "Accept": "application/vnd.github+json",
                    "X-GitHub-Api-Version": "2022-11-28",
                },
                json=pr_data,
            )
    except Exception as exc:
        return {
            "success": False,
            "data": {"branch": branch_name},
            "error": f"GitHub API request failed: {exc}",
        }

    if resp.status_code == 201:
        pr_url = resp.json().get("html_url", "")
        return {
            "success": True,
            "data": {"pr_url": pr_url, "branch": branch_name, "status": "success"},
            "error": None,
        }
    elif resp.status_code == 422:
        return {
            "success": True,
            "data": {"pr_url": "", "branch": branch_name, "status": "already_exists"},
            "error": None,
        }
    else:
        return {
            "success": False,
            "data": {"branch": branch_name},
            "error": f"PR creation failed ({resp.status_code}): {resp.text}",
        }


# ---------------------------------------------------------------------------
# Action handler registry
# ---------------------------------------------------------------------------

ACTION_HANDLERS: dict[str, Any] = {
    "dapr-swe/initialize": handle_initialize,
    "dapr-swe/plan": handle_plan,
    "dapr-swe/develop": handle_develop,
    "dapr-swe/review": handle_review,
    "dapr-swe/commit-pr": handle_commit_pr,
}
